# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyU5p7NOZQONrk15pG7-uoEMLD7SP2IO
"""

# data types
# str = string = to write/keep text
print ("hello 8C")
print ('hello 8C')
# numeric types: intergers (int), float
print ('8.5')
print ("8")

# mathematic operator + - / % * (addition, substaction, division, mod, multiplication)
print("8C" + "ms ivonne")
print(3 + 20)
print("3" + "20")

# variables= naming
# in python = case sensitive
# ways on right variables = ur'e allowed to start with number
# not put a space in between
# 8C = 20 -> wrong
# eight c = 20 -> wrong
fried_fish = 100
fied_fish = 90
fried_fish = 70
fried_fish = 65
print(friedfish, friedfish)

# input = determined the data types
name = input("please type your name:")
print("sooo your name is....")

name = input("please type your name:")
print("sooo your name is...." ,name, "?")
age = input("please input your age: ")
print("sooo ur age is....",age, "?")
print("hi" + " charlene" + " you" + " are" + " 12" +  " years" + " old")